#create a k8s StatefulSet with name 'mongodb'
#this statefulset will create only 1 pod (1 replica)
#this statefulset will use headless service named 'mongodb' and will create pods with label 'type:db'
#container created in the pod will use 'mongo:latest' image and will have name of 'mongodb'
#each container will have env variables: 'MONGO_INITDB_ROOT_USERNAME_FILE' and 'MONGO_INITDB_ROOT_PASSWORD_FILE'
#the value of env variable is retrieved from /etc/mongo-credentials directory
#this directory is mounted from 'mongodb-secret-mount' volume
#other than that, the container will also have its '/data/db' folder mounted from 'mongodb-persistent-storage' pv
#finally, the container will also have its '/config' directory mounted with 'mongodb-config-mount' volume,
#'mongo.conf' file will be created in that directory and contain the value of the created configmap 'mongodb-config'
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      type: db
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: mongo:latest
          name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
            - name: mongodb-secret-mount
              mountPath: /etc/mongo-credentials
            - name: mongodb-config-mount
              mountPath: /config
              readOnly: true
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
        - name: mongodb-secret-mount
          secret:
            secretName: mongodb-secret
        - name: mongodb-config-mount
          configMap:
            name: mongodb-config
            items:
              - key: mongo.conf
                path: mongo.conf
