# create a k8s Secret with name 'mongodb-secret' that contains two data:
# MONGO_ROOT_USERNAME: will be used as a username when logging in to the mongodb
# MONGO_ROOT_PASSWORD: is a base64-encoded string from 'supersecretpassword'
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
stringData:
  MONGO_ROOT_USERNAME: admin
data:
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
